language: go

sudo: false

services:
  - docker

go:
  - 1.7

script:
  - make test-coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - mkdir -p $HOME/.docker/
  - openssl aes-256-cbc -K $encrypted_55ba33ebd2bf_key -iv $encrypted_55ba33ebd2bf_iv -in .docker.json.enc -out $HOME/.docker/config.json -d
  - make push
  - make packages

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - build/gopkg_${TRAVIS_TAG}_darwin_amd64.tar.gz
    - build/gopkg_${TRAVIS_TAG}_linux_amd64.tar.gz
  skip_cleanup: true
  on:
    tags: true
